CREATE TYPE "role_type" AS ENUM (
  'admin',
  'customer'
);

CREATE TYPE "refund_status" AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TABLE "users" (
  "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  "role" role_type DEFAULT 'customer',
  "email" text UNIQUE NOT NULL,
  "password" text NOT NULL,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "transactions" (
  "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "payment_id" int NOT NULL,
  "total_payment" int,
  "paid_at" timestamptz,
  "scanned_at" timestamptz,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "schedule_id" int
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "method" text NOT NULL
);

CREATE TABLE "cinemas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL
);

CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "movies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "deleted_at" timestamptz,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "seats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cinema_id" int,
  "row_label" varchar(2),
  "column_number" int
);

CREATE TABLE "schedules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" int NOT NULL,
  "cinema_id" int NOT NULL,
  "movie_id" int NOT NULL,
  "start_at" time,
  "ticket_price" int NOT NULL,
  "show_date" date NOT NULL
);

CREATE TABLE "seats_schedules" (
  "seats_id" int,
  "schedule_id" int,
  "transactions_id" uuid
);

CREATE TABLE "refund_requests" (
  "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  "transaction_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "reason" text,
  "amount" int NOT NULL,
  "status" refund_status DEFAULT 'pending',
  "processed_by" uuid,
  "processed_at" timestamptz,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

ALTER TABLE "refund_requests" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "refund_requests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "refund_requests" ADD FOREIGN KEY ("processed_by") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("schedule_id") REFERENCES "schedules" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("cinema_id") REFERENCES "cinemas" ("id");

ALTER TABLE "seats_schedules" ADD FOREIGN KEY ("transactions_id") REFERENCES "transactions" ("id");

ALTER TABLE "seats_schedules" ADD FOREIGN KEY ("seats_id") REFERENCES "seats" ("id");

ALTER TABLE "seats" ADD FOREIGN KEY ("cinema_id") REFERENCES "cinemas" ("id");

