-- public.cinemas definition

-- Drop table

-- DROP TABLE public.cinemas;

CREATE TABLE public.cinemas (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT cinemas_pkey PRIMARY KEY (id)
);


-- public.cities definition

-- Drop table

-- DROP TABLE public.cities;

CREATE TABLE public.cities (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT cities_name_key UNIQUE (name),
	CONSTRAINT cities_pkey PRIMARY KEY (id)
);


-- public.movies definition

-- Drop table

-- DROP TABLE public.movies;

CREATE TABLE public.movies (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title text NOT NULL,
	deleted_at timestamptz NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT movies_pkey PRIMARY KEY (id)
);


-- public.payments definition

-- Drop table

-- DROP TABLE public.payments;

CREATE TABLE public.payments (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"method" text NOT NULL,
	CONSTRAINT payments_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"role" public."role_type" DEFAULT 'customer'::role_type NULL,
	email text NOT NULL,
	"password" text NOT NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.schedules definition

-- Drop table

-- DROP TABLE public.schedules;

CREATE TABLE public.schedules (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city_id int4 NOT NULL,
	cinema_id int4 NOT NULL,
	movie_id int4 NOT NULL,
	start_at time NULL,
	ticket_price int4 NOT NULL,
	show_date date NOT NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT schedules_pkey PRIMARY KEY (id),
	CONSTRAINT schedules_cinema_id_fkey FOREIGN KEY (cinema_id) REFERENCES public.cinemas(id),
	CONSTRAINT schedules_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
	CONSTRAINT schedules_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(id)
);


-- public.seats definition

-- Drop table

-- DROP TABLE public.seats;

CREATE TABLE public.seats (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cinema_id int4 NULL,
	row_label varchar(2) NULL,
	column_number int4 NULL,
	CONSTRAINT seats_pkey PRIMARY KEY (id),
	CONSTRAINT seats_cinema_id_fkey FOREIGN KEY (cinema_id) REFERENCES public.cinemas(id)
);


-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	user_id uuid NOT NULL,
	payment_id int4 NOT NULL,
	total_payment int4 NULL,
	paid_at timestamptz NULL,
	scanned_at timestamptz NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	schedule_id int4 NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id),
	CONSTRAINT transactions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
	CONSTRAINT transactions_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id),
	CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.refund_requests definition

-- Drop table

-- DROP TABLE public.refund_requests;

CREATE TABLE public.refund_requests (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	transaction_id uuid NOT NULL,
	user_id uuid NOT NULL,
	reason text NULL,
	amount int4 NOT NULL,
	status public."refund_status" DEFAULT 'pending'::refund_status NULL,
	processed_by uuid NULL,
	processed_at timestamptz NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT refund_requests_pkey PRIMARY KEY (id),
	CONSTRAINT refund_requests_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id),
	CONSTRAINT refund_requests_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
	CONSTRAINT refund_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.seats_schedules definition

-- Drop table

-- DROP TABLE public.seats_schedules;

CREATE TABLE public.seats_schedules (
	seats_id int4 NULL,
	schedule_id int4 NULL,
	transactions_id uuid NULL,
	CONSTRAINT seats_schedules_seats_id_fkey FOREIGN KEY (seats_id) REFERENCES public.seats(id),
	CONSTRAINT seats_schedules_transactions_id_fkey FOREIGN KEY (transactions_id) REFERENCES public.transactions(id)
);